bo :
    driver   : mysql
    host     : db.local.dkr.pluie.org
    dbname   : local_bo_sub
    user     : dev
    password : mysql
    charset  : utf8
    port     : 3306

therapy :
    driver   : mysql
    host     : db.local.dkr.pluie.org
    dbname   : local_therapy
    user     : dev
    password : mysql
    charset  : utf8
    port     : 3306
